import { StyleSheet } from "react-native";

import { colors } from "../../theme/colors";
import { radius, shadow, spacing } from "../../theme/layout";
import { typography } from "../../theme/typography";

export const profileStyles = StyleSheet.create({
  loadingContainer: {
    justifyContent: "center",
  },
  content: {
    paddingBottom: spacing["3xl"],
    backgroundColor: colors.background,
  },
  hero: {
    minHeight: 242,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.xl,
    paddingTop: spacing["2xl"],
    paddingBottom: spacing.xl,
  },
  avatar: {
    width: 94,
    height: 94,
    borderRadius: radius.full,
    backgroundColor: colors.primarySoft,
    borderWidth: 4,
    borderColor: "rgba(255,255,255,0.48)",
    alignItems: "center",
    justifyContent: "center",
    ...shadow.md,
  },
  avatarPressed: {
    opacity: 0.86,
    transform: [{ scale: 0.98 }],
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: radius.full,
    resizeMode: "cover",
  },
  avatarText: {
    fontSize: 31,
    fontWeight: "900",
    color: colors.primaryDark,
  },
  cameraBadge: {
    position: "absolute",
    right: 2,
    bottom: 4,
    width: 29,
    height: 29,
    borderRadius: radius.full,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(14,165,233,0.24)",
    ...shadow.sm,
  },
  identity: {
    marginTop: spacing.sm,
    alignItems: "center",
    width: "100%",
  },
  nameRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    maxWidth: "100%",
  },
  name: {
    maxWidth: "84%",
    fontSize: 20,
    fontWeight: "900",
    color: colors.textInverse,
  },
  nameEditButton: {
    width: 28,
    height: 28,
    borderRadius: radius.full,
    alignItems: "center",
    justifyContent: "center",
  },
  email: {
    marginTop: spacing.xs,
    fontSize: 13,
    fontWeight: "600",
    color: "rgba(255,255,255,0.86)",
  },
  rolePill: {
    marginTop: 7,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "rgba(255,255,255,0.16)",
    paddingHorizontal: spacing.md,
    paddingVertical: 6,
    borderRadius: radius.full,
  },
  roleText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.textInverse,
  },
  body: {
    marginTop: -20,
    paddingHorizontal: spacing.xl,
    gap: spacing.lg,
  },
  errorCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.dangerSoft,
    borderColor: colors.danger,
    borderWidth: 1,
    borderRadius: radius.md,
    padding: spacing.md,
  },
  errorText: {
    flex: 1,
    fontSize: 12,
    fontWeight: "600",
    color: colors.dangerDark,
  },
  section: {
    gap: spacing.sm,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: colors.text,
  },
  statsBox: {
    minHeight: 88,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    ...shadow.md,
  },
  statItem: {
    flex: 1,
    alignItems: "center",
    gap: 3,
  },
  statValue: {
    fontSize: 15,
    fontWeight: "900",
    color: colors.text,
  },
  statLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: colors.textSoft,
  },
  statDivider: {
    position: "absolute",
    right: 0,
    top: 12,
    bottom: 12,
    width: 1,
    backgroundColor: colors.border,
  },
  accountRow: {
    minHeight: 68,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  accountIcon: {
    width: 42,
    height: 42,
    borderRadius: radius.full,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primarySoft,
  },
  accountText: {
    flex: 1,
    minWidth: 0,
  },
  accountLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.textSoft,
  },
  accountValue: {
    marginTop: 2,
    fontSize: 14,
    fontWeight: "800",
    color: colors.text,
  },
  accountNameInput: {
    minHeight: 42,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: spacing.md,
    fontSize: 14,
    fontWeight: "700",
    color: colors.text,
  },
  editNameButton: {
    width: 36,
    height: 36,
    borderRadius: radius.full,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.surfaceMuted,
  },
  inlineActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
  },
  inlineActionButton: {
    width: 36,
    height: 36,
    borderRadius: radius.full,
    alignItems: "center",
    justifyContent: "center",
  },
  btnSuccess: {
    backgroundColor: colors.success,
  },
  btnDanger: {
    backgroundColor: colors.danger,
  },
  badgeGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: spacing.sm,
  },
  badgeItem: {
    flex: 1,
    alignItems: "center",
    gap: 6,
  },
  badgeItemMuted: {
    opacity: 0.52,
  },
  badgeIcon: {
    width: 44,
    height: 44,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: "rgba(14,165,233,0.16)",
    alignItems: "center",
    justifyContent: "center",
  },
  badgeLabel: {
    fontSize: 9.5,
    lineHeight: 13,
    fontWeight: "700",
    color: colors.textMuted,
    textAlign: "center",
  },
  settingsCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    overflow: "hidden",
    ...shadow.sm,
  },
  settingsRow: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: 7,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  settingsRowBusy: {
    opacity: 0.74,
  },
  languageRow: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: 7,
  },
  settingsIcon: {
    width: 38,
    height: 38,
    borderRadius: radius.full,
    backgroundColor: colors.primarySoft,
    alignItems: "center",
    justifyContent: "center",
  },
  settingsText: {
    flex: 1,
    minWidth: 0,
  },
  settingsTitle: {
    fontSize: 13,
    fontWeight: "900",
    color: colors.text,
  },
  settingsSubtitle: {
    marginTop: 2,
    fontSize: 11,
    fontWeight: "700",
    color: "#7684B0",
  },
  languageSwitch: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: radius.full,
    backgroundColor: colors.surfaceMuted,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 3,
  },
  languageOption: {
    minWidth: 34,
    minHeight: 28,
    borderRadius: radius.full,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing.sm,
  },
  languageOptionActive: {
    backgroundColor: colors.primary,
  },
  languageOptionText: {
    fontSize: 11,
    fontWeight: "900",
    color: colors.textSoft,
  },
  languageOptionTextActive: {
    color: colors.textInverse,
  },
  logoutButton: {
    minHeight: 48,
    borderRadius: radius.lg,
    backgroundColor: colors.dangerSoft,
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.24)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
  },
  logoutButtonText: {
    fontSize: 14,
    fontWeight: "900",
    color: colors.danger,
  },
  inlineActionPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.98 }],
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: spacing.xl,
  },
  modalContainer: {
    width: "100%",
    backgroundColor: colors.surface,
    borderRadius: radius.xl,
    padding: spacing.xl,
    alignItems: "center",
    gap: spacing.md,
    ...shadow.md,
  },
  modalIconWrap: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.dangerSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.text,
    textAlign: "center",
  },
  modalMessage: {
    ...typography.body,
    color: colors.textMuted,
    textAlign: "center",
    marginBottom: spacing.md,
  },
  nameInput: {
    width: "100%",
    height: 46,
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: radius.md,
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: spacing.md,
    fontSize: 15,
    fontWeight: "700",
    color: colors.text,
  },
  modalBtnRow: {
    flexDirection: "row",
    gap: spacing.md,
    width: "100%",
  },
  modalBtnCancel: {
    flex: 1,
    height: 48,
  },
  modalBtnLogout: {
    flex: 1,
    height: 48,
  },
});
