export const REPORT_ALLOWED_DISTANCE_METERS = 20;
export const VERIFICATION_DISTANCE_METERS = 80;
export const WARNING_DISTANCE_METERS = 700;
export const LOCAL_INCIDENT_NOTIFICATION_DISTANCE_METERS = 300;
