import type { IncidentSubcategory } from "../../types/incident";
import type { IncidentMeta } from "./types";

export const INCIDENT_TYPES = {
  flood: {
    category: "natural_disaster",
    label: "Flood",
    shortLabel: "Flood",
    iconName: "water",
    color: "#2F5C50",
    lightColor: "#E2ECE9",
  },
  earthquake: {
    category: "natural_disaster",
    label: "Earthquake",
    shortLabel: "Quake",
    iconName: "pulse",
    color: "#705C30",
    lightColor: "#F5ECD7",
  },
  landslide: {
    category: "natural_disaster",
    label: "Landslide",
    shortLabel: "Slide",
    iconName: "trail-sign",
    color: "#5E4D2B",
    lightColor: "#F0ECE4",
  },
  volcanic_eruption: {
    category: "natural_disaster",
    label: "Volcanic Eruption",
    shortLabel: "Volcano",
    iconName: "flame",
    color: "#B83230",
    lightColor: "#FADCDA",
  },
  strong_wind: {
    category: "natural_disaster",
    label: "Strong Wind",
    shortLabel: "Wind",
    iconName: "cloudy",
    color: "#74796E",
    lightColor: "#ECE9E5",
  },
  tsunami: {
    category: "natural_disaster",
    label: "Tsunami",
    shortLabel: "Tsunami",
    iconName: "radio",
    color: "#1B3B32",
    lightColor: "#D1E3DF",
  },
  fire: {
    category: "fire_emergency",
    label: "General Fire",
    shortLabel: "Fire",
    iconName: "flame",
    color: "#B83230",
    lightColor: "#FADCDA",
  },
  building_fire: {
    category: "fire_emergency",
    label: "House / Building Fire",
    shortLabel: "Building",
    iconName: "home",
    color: "#B83230",
    lightColor: "#FADCDA",
  },
  vehicle_fire: {
    category: "fire_emergency",
    label: "Vehicle Fire",
    shortLabel: "Vehicle",
    iconName: "car-sport",
    color: "#8D1B1B",
    lightColor: "#FADCDA",
  },
  land_fire: {
    category: "fire_emergency",
    label: "Land Fire",
    shortLabel: "Land",
    iconName: "flame",
    color: "#705C30",
    lightColor: "#F5ECD7",
  },
  electrical_fire: {
    category: "fire_emergency",
    label: "Electrical Fire",
    shortLabel: "Electric",
    iconName: "flash",
    color: "#8D6B1E",
    lightColor: "#FDF5E2",
  },
  traffic_accident: {
    category: "accident_infrastructure",
    label: "Traffic Accident",
    shortLabel: "Accident",
    iconName: "car-sport",
    color: "#705C30",
    lightColor: "#F5ECD7",
  },
  fallen_tree: {
    category: "accident_infrastructure",
    label: "Fallen Tree",
    shortLabel: "Tree",
    iconName: "leaf",
    color: "#4A7C59",
    lightColor: "#E2ECE3",
  },
  road_block: {
    category: "accident_infrastructure",
    label: "Road Block",
    shortLabel: "Blocked",
    iconName: "trail-sign",
    color: "#705C30",
    lightColor: "#F5ECD7",
  },
  damaged_road: {
    category: "accident_infrastructure",
    label: "Damaged Road",
    shortLabel: "Road",
    iconName: "construct",
    color: "#705C30",
    lightColor: "#F5ECD7",
  },
  fallen_power_line: {
    category: "accident_infrastructure",
    label: "Downed Power Line",
    shortLabel: "Cable",
    iconName: "flash",
    color: "#8D6B1E",
    lightColor: "#FDF5E2",
  },
  collapsed_building: {
    category: "accident_infrastructure",
    label: "Collapsed Building",
    shortLabel: "Collapse",
    iconName: "business",
    color: "#705C30",
    lightColor: "#F5ECD7",
  },
  crime: {
    category: "security_public_order",
    label: "Crime",
    shortLabel: "Crime",
    iconName: "shield",
    color: "#8D1B1B",
    lightColor: "#FCEAE8",
  },
  theft: {
    category: "security_public_order",
    label: "Theft",
    shortLabel: "Theft",
    iconName: "lock-closed",
    color: "#8D1B1B",
    lightColor: "#FCEAE8",
  },
  brawl: {
    category: "security_public_order",
    label: "Fight / Brawl",
    shortLabel: "Brawl",
    iconName: "people",
    color: "#8D1B1B",
    lightColor: "#FCEAE8",
  },
  risky_crowd: {
    category: "security_public_order",
    label: "Risky Crowd",
    shortLabel: "Crowd",
    iconName: "people",
    color: "#704A8D",
    lightColor: "#F5EAFE",
  },
  mob_violence: {
    category: "security_public_order",
    label: "Mob Violence",
    shortLabel: "Mob",
    iconName: "people-circle",
    color: "#8D1B1B",
    lightColor: "#FCEAE8",
  },
  public_disturbance: {
    category: "security_public_order",
    label: "Public Disturbance",
    shortLabel: "Disturb",
    iconName: "megaphone",
    color: "#704A8D",
    lightColor: "#F5EAFE",
  },
  medical: {
    category: "medical_rescue",
    label: "Medical Emergency",
    shortLabel: "Medical",
    iconName: "medkit",
    color: "#4A7C59",
    lightColor: "#E2ECE3",
  },
  fainted_person: {
    category: "medical_rescue",
    label: "Fainted Person",
    shortLabel: "Faint",
    iconName: "person",
    color: "#4A7C59",
    lightColor: "#E2ECE3",
  },
  work_accident: {
    category: "medical_rescue",
    label: "Workplace Accident",
    shortLabel: "Work",
    iconName: "hammer",
    color: "#4A7C59",
    lightColor: "#E2ECE3",
  },
  drowning: {
    category: "medical_rescue",
    label: "Drowning",
    shortLabel: "Drown",
    iconName: "water",
    color: "#4A7C59",
    lightColor: "#E2ECE3",
  },
  evacuation_needed: {
    category: "medical_rescue",
    label: "Evacuation Needed",
    shortLabel: "Evacuate",
    iconName: "alert-circle",
    color: "#B83230",
    lightColor: "#FADCDA",
  },
  missing_person: {
    category: "missing_lost",
    label: "Missing Person",
    shortLabel: "Missing",
    iconName: "person-outline",
    color: "#6A5320",
    lightColor: "#F5ECD7",
  },
  missing_item: {
    category: "missing_lost",
    label: "Lost Item",
    shortLabel: "Item",
    iconName: "bag-handle-outline",
    color: "#6A5320",
    lightColor: "#F5ECD7",
  },
  missing_vehicle: {
    category: "missing_lost",
    label: "Missing Vehicle",
    shortLabel: "Vehicle",
    iconName: "car-outline",
    color: "#6A5320",
    lightColor: "#F5ECD7",
  },
  other_incident: {
    category: "other",
    label: "Other Incident",
    shortLabel: "Other",
    iconName: "help-circle",
    color: "#74796E",
    lightColor: "#ECE9E5",
  },
} as const satisfies Record<IncidentSubcategory, IncidentMeta>;
