import { StyleSheet } from "react-native";

import { colors } from "../theme/colors";
import { radius, shadow, spacing } from "../theme/layout";
import { typography } from "../theme/typography";

export const mapStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#0C7186",
  },
  container: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  header: {
    minHeight: 122,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing["2xl"],
    paddingBottom: spacing.lg,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  headerTextGroup: {
    flex: 1,
    minWidth: 0,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: colors.textInverse,
  },
  headerSubtitle: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: "700",
    color: "rgba(255,255,255,0.88)",
  },
  filterIconButton: {
    width: 44,
    height: 44,
    borderRadius: radius.full,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.18)",
  },
  filterShell: {
    minHeight: 58,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    justifyContent: "center",
  },
  mapPanel: {
    flex: 1,
    backgroundColor: colors.surfaceMuted,
    overflow: "hidden",
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(248,250,252,0.76)",
  },
  errorBanner: {
    position: "absolute",
    top: spacing.md,
    left: spacing.lg,
    right: spacing.lg,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.dangerSoft,
    borderRadius: radius.lg,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.14)",
    ...shadow.card,
  },
  errorText: {
    flex: 1,
    ...typography.caption,
    color: colors.dangerDark,
  },
  mapActions: {
    position: "absolute",
    right: spacing.lg,
    bottom: spacing.lg,
    alignItems: "center",
    gap: spacing.sm,
  },
  roundActionButton: {
    width: 52,
    height: 52,
    borderRadius: radius.full,
    backgroundColor: colors.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    ...shadow.md,
  },
  reportActionButton: {
    width: 52,
    height: 52,
    borderRadius: radius.full,
    backgroundColor: colors.danger,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: colors.surface,
    ...shadow.floating,
    shadowColor: colors.dangerDark,
  },
  sosActionButton: {
    width: 44,
    height: 44,
    borderRadius: radius.full,
    backgroundColor: "#0C7186",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.88)",
    ...shadow.card,
  },
  iconButtonPressed: {
    opacity: 0.84,
    transform: [{ scale: 0.96 }],
  },
  legendBar: {
    minHeight: 52,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.md,
  },
  legendGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendDot: {
    width: 12,
    height: 12,
    borderRadius: radius.full,
  },
  legendText: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.textMuted,
  },
  visibleCount: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    flexShrink: 1,
  },
  visibleCountText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#4B658A",
  },
  statusStrip: {
    minHeight: 30,
    paddingHorizontal: spacing.xl,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: radius.full,
    backgroundColor: colors.success,
  },
  statusStripText: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.textSoft,
  },
  unavailableContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.md,
    paddingHorizontal: spacing["2xl"],
    backgroundColor: colors.surface,
  },
  unavailableIcon: {
    width: 72,
    height: 72,
    borderRadius: radius.full,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.primarySoft,
  },
  unavailableTitle: {
    ...typography.sectionTitle,
    color: colors.text,
    textAlign: "center",
  },
  unavailableMessage: {
    ...typography.body,
    maxWidth: 360,
    color: colors.textMuted,
    textAlign: "center",
  },
  unavailableButton: {
    marginTop: spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    borderRadius: radius.lg,
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  unavailableButtonText: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.textInverse,
  },
});
